name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.koushik1207 }}
          password: ${{ secrets.koushikdjack@12 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.koushik1207 }}/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIA4MTWMCX6NFO2K7LI }}
          aws-secret-access-key: ${{ secrets.kapjZ+OQQR4KPAsZIrIWZTMZMHpPhfPPtUnazgC+ }}
          aws-region: us-east-1

      - name: Deploy to ECS
        run: |
          ecs-cli configure --cluster my-cluster --default-launch-type EC2 --region us-east-1 --config-name my-config
          ecs-cli compose --file docker-compose.yml up

