version: '3'
services:
  web:
    image: my-dockerhub-username/my-app:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

